### PR TITLE
Nav cms

### PR DESCRIPTION
**Pull request by mcheng09**
Navigation is new configurable via menu on WP. The caveat is we have to use custom links due to the data not returning a parent slug if it's a child. 

i.e. Banquet Facility slug = `/banquet-facility.` I want `/about/banquet-facility`

Feel free to reach out to me if you want me details. The current menu on the WP backend follows the Phase 1 routes in the route reducer.

### CODE REVIEW

**Comment by mcheng09** [comment]
FYI, there seems to be a lot of changes going through. If this looks good, I'm going to create a fresh branch with the newest version of Main and transfer the changes from there.

**Comment by mcheng09** [comment]
Going to hold this off until after the presentation. Will need to branch off the newest version of Develop and create a new PR through there. In the meantime, feel free to give me any feedback.

**Comment by mattlaguardia** [comment]
yea tbh im wasnt planning on looking at this until after anyways - youre gonna have a bunch of merge conflicts lol

**Comment by mattlaguardia** [comment]
Closing this

**Pull request closed without merging**
